### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by pbauermeister** [pbauermeister/ScanTube#3]

**Comment by richardbmx** [comment]
@pbauermeister  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by pbauermeister** [comment]
Basic launcher icon added in a25cf61d68aba33a683987bc1b51124f767460ad
